name: heal and Feed
main: Pooyan3748\heal\Main
version: 1.0.0
api: 5.0.0
auther: Pooyan3748

commands:

  heal:
    description: "Your heal is full"
    permission: heal.cmd

  feed:
    description: "Your food is full"
    permission: feed.cmd

permissions: 
  heal.cmd:
    description: "Your heal is full"
    default: op 
  feed.cmd:
    description: "Your food is full"
    default: op

